Revert "Shallower subheading labelling"
UBC-DSCI/introduction-to-datascience-python pull request #246
Opened 2023-09-13 23:22 UTC by joelostblom

@trevorcampbell I just realized something after you merged https://github.com/UBC-DSCI/introduction-to-datascience-python/pull/245. The heading level to number was already set to 3, so we shouldn't need to set it to 2, since the heading we are trying to control is a fourth level heading. I think what actually is happening is that jupyter book does not allow non-consecutive jumps in headings levels. So since we went from a second level to a fourth level heading in the viz chapter, the latter was promoted to a third level heading which used to be numbered in the old config. I don't know if there is a way around this in jupyter book and allow for non-consecutive jumps, but we should revert that PR since it causes an issue with all other third level headings which are not longer numbered
![image](https://github.com/UBC-DSCI/introduction-to-datascience-python/assets/4560057/b116fb5d-03e9-48be-beab-5e128ffee01b)

2023-09-13 23:25 UTC, trevorcampbell commented
Ah! Huh. I noticed the 3 vs 4 problem too, but I figured the "chapter-level" headings were implicitly "0", so 3->2 made sense.

But yeah I see this broke some things. Thanks for double checking that.

2023-09-13 23:27 UTC, trevorcampbell requested changes
This looks good, but we should try to fix the problem with the viz section here

Can we just use bold+italics for those subheadings? instead of trying to keep them with `#### blah` ?

Or does `{-}` solve it? https://stackoverflow.com/questions/35077571/how-to-remove-heading-numbers-in-jupyter-during-pdf-conversion

2023-09-14 23:44 UTC, joelostblom commented
> Or does {-} solve it

Unfortunately it didn't

This is what bold + italics look like. Not the prettiest, but I'm OK with it. Thoughts?

![image](https://github.com/UBC-DSCI/introduction-to-datascience-python/assets/4560057/1d273f5b-e313-4906-8cb1-3430dbff6fff)

2023-09-15 00:16 UTC, trevorcampbell commented
We can use font to do it -- looks like this. I committed it already -- if you're happy with it we can merge

![image](https://github.com/UBC-DSCI/introduction-to-datascience-python/assets/5981307/83fd7529-e5c9-4880-b81a-ed031ea20d81)

2023-09-15 00:21 UTC, trevorcampbell approved these changes
LGTM now (also this just becomes italics in the PDF build, which also looks fine -- better than bold+italics IMO)

2023-09-15 02:03 UTC, joelostblom commented
Great solution and thanks for updating the PR; merging.

2023-09-15 02:03 UTC, merged