[WIP] Chapter 6 production polish
UBC-DSCI/introduction-to-datascience-python pull request #86
Opened 2023-01-02 06:48 UTC by trevorcampbell

WIP

- closes #70 
- closes #9

2023-01-09 07:27 UTC, trevorcampbell commented
@joelostblom there is one figure at the end (Figure 6.7) that is not generating properly --- see the R version to see what the plot should look like). Your help there would be much appreciated.

Aside from that @joelostblom and @lheagy this is ready for review.

Please review the Ch5 PR first #78 since this builds on that one.

2023-01-13 15:03 UTC, joelostblom requested changes
Looking good overall! My biggest comment is the one I made in the issues regarding randomness.

2023-01-13 15:03 UTC, joelostblom commented on source/classification2.md
> -- Set the random seed in Python using the `numpy.random.seed` function or `random_state` argument in some of the `scikit-learn` functions.
See the note I added in https://github.com/UBC-DSCI/introduction-to-datascience-python/issues/114 for some more thoughts on this.

2023-01-13 15:03 UTC, joelostblom commented on source/classification2.md
> +cancer['Class'] = cancer['Class'].astype('category')
```suggestion
cancer['Class'] = cancer['Class'].replace({
    'M' : 'Malignant',
    'B' : 'Benign'
}).astype('category')
```

2023-01-13 15:03 UTC, joelostblom commented on source/classification2.md
> +random_numbers1 = nums_0_to_9.sample(n = 10).values
`values` will be deprecated in favor of `to_numpy()` so it would be preferred if we use that I think

2023-01-13 15:03 UTC, joelostblom commented on source/classification2.md
>      .mark_point(opacity=0.6, filled=True, size=40)
```suggestion
    .mark_circle()
```

2023-01-13 15:03 UTC, joelostblom commented on source/classification2.md
> +cancer_train["Class"].value_counts(normalize = True)
```suggestion
cancer_train["Class"].value_counts(normalize=True)
```

2023-01-13 15:03 UTC, joelostblom commented on source/classification2.md
> +                  ))
```suggestion
cancer_test_predictions = cancer_test.assign(
    predicted = knn_fit.predict(cancer_test.loc[:, ["Smoothness", "Concavity"]])
)
```

2023-01-13 15:03 UTC, joelostblom commented on source/classification2.md
> +    ]
```suggestion
]
```

2023-01-13 15:03 UTC, joelostblom commented on source/classification2.md
> +len(correct_preds) / len(cancer_test_predictions)
```suggestion
correct_preds.shape[0] / cancer_test_predictions.shape[0]
```

2023-01-13 15:03 UTC, joelostblom commented on source/classification2.md
> +              )
```suggestion
cancer_acc_1 = knn_fit.score(
    cancer_test.loc[:, ["Smoothness", "Concavity"]],
    cancer_test["Class"]
)
```

2023-01-13 15:03 UTC, joelostblom commented on source/classification2.md
> +           )
```suggestion
pd.crosstab(
    cancer_test_predictions["Class"],
    cancer_test_predictions["predicted"]
)
```

2023-01-13 15:03 UTC, joelostblom commented on source/classification2.md
> +cancer_train["Class"].value_counts(normalize = True)
```suggestion
cancer_train["Class"].value_counts(normalize=True)
```

2023-01-13 15:03 UTC, joelostblom commented on source/classification2.md
> +       )
```suggestion
acc = knn_fit.score(
    cancer_validation.loc[:, ["Smoothness", "Concavity"]],
    cancer_validation["Class"]
)
```

2023-01-13 15:03 UTC, joelostblom commented on source/classification2.md
> +alt.renderers.enable("mimetype")
```suggestion
```

This uses jupyterlab to insert a png as a backup image for charts and a vega-lite instead of html representation of the interactive version of the chart. Since jupyter-book does not call jupyterlab in anyway, the image is not create and the browser can't handle the vega-lite spec, but needs the html version so we'll leave it with the original renderer for now.

2023-01-18 18:48 UTC, trevorcampbell commented on source/classification2.md
> -- Set the random seed in Python using the `numpy.random.seed` function or `random_state` argument in some of the `scikit-learn` functions.
I'm going to stick with the current `np.random.seed` approach as discussed in #114

2023-01-18 18:49 UTC, trevorcampbell commented on source/classification2.md
> +random_numbers1 = nums_0_to_9.sample(n = 10).values
good call!

2023-01-18 19:01 UTC, merged